package blockchain

const poolABIJSON = `[
  {"inputs":[],"name":"slot0","outputs":[
    {"internalType":"uint160","name":"sqrtPriceX96","type":"uint160"},
    {"internalType":"int24","name":"tick","type":"int24"},
    {"internalType":"uint16","name":"observationIndex","type":"uint16"},
    {"internalType":"uint16","name":"observationCardinality","type":"uint16"},
    {"internalType":"uint16","name":"observationCardinalityNext","type":"uint16"},
    {"internalType":"uint8","name":"feeProtocol","type":"uint8"},
    {"internalType":"bool","name":"unlocked","type":"bool"}
  ],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"liquidity","outputs":[{"internalType":"uint128","name":"","type":"uint128"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"token0","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"token1","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"fee","outputs":[{"internalType":"uint24","name":"","type":"uint24"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"tickSpacing","outputs":[{"internalType":"int24","name":"","type":"int24"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"int24","name":"","type":"int24"}],"name":"ticks","outputs":[
    {"internalType":"uint128","name":"liquidityGross","type":"uint128"},
    {"internalType":"int128","name":"liquidityNet","type":"int128"},
    {"internalType":"uint256","name":"feeGrowthOutside0X128","type":"uint256"},
    {"internalType":"uint256","name":"feeGrowthOutside1X128","type":"uint256"},
    {"internalType":"int56","name":"tickCumulativeOutside","type":"int56"},
    {"internalType":"uint160","name":"secondsPerLiquidityOutsideX128","type":"uint160"},
    {"internalType":"uint32","name":"secondsOutside","type":"uint32"},
    {"internalType":"bool","name":"initialized","type":"bool"}
  ],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"int16","name":"","type":"int16"}],"name":"tickBitmap","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"anonymous":false,"inputs":[
    {"indexed":false,"internalType":"uint160","name":"sqrtPriceX96","type":"uint160"},
    {"indexed":false,"internalType":"int24","name":"tick","type":"int24"}
  ],"name":"Initialize","type":"event"},
  {"anonymous":false,"inputs":[
    {"indexed":true,"internalType":"address","name":"sender","type":"address"},
    {"indexed":true,"internalType":"address","name":"recipient","type":"address"},
    {"indexed":false,"internalType":"int256","name":"amount0","type":"int256"},
    {"indexed":false,"internalType":"int256","name":"amount1","type":"int256"},
    {"indexed":false,"internalType":"uint160","name":"sqrtPriceX96","type":"uint160"},
    {"indexed":false,"internalType":"uint128","name":"liquidity","type":"uint128"},
    {"indexed":false,"internalType":"int24","name":"tick","type":"int24"}
  ],"name":"Swap","type":"event"},
  {"anonymous":false,"inputs":[
    {"indexed":false,"internalType":"address","name":"sender","type":"address"},
    {"indexed":true,"internalType":"address","name":"owner","type":"address"},
    {"indexed":true,"internalType":"int24","name":"tickLower","type":"int24"},
    {"indexed":true,"internalType":"int24","name":"tickUpper","type":"int24"},
    {"indexed":false,"internalType":"uint128","name":"amount","type":"uint128"},
    {"indexed":false,"internalType":"uint256","name":"amount0","type":"uint256"},
    {"indexed":false,"internalType":"uint256","name":"amount1","type":"uint256"}
  ],"name":"Mint","type":"event"},
  {"anonymous":false,"inputs":[
    {"indexed":true,"internalType":"address","name":"owner","type":"address"},
    {"indexed":true,"internalType":"int24","name":"tickLower","type":"int24"},
    {"indexed":true,"internalType":"int24","name":"tickUpper","type":"int24"},
    {"indexed":false,"internalType":"uint128","name":"amount","type":"uint128"},
    {"indexed":false,"internalType":"uint256","name":"amount0","type":"uint256"},
    {"indexed":false,"internalType":"uint256","name":"amount1","type":"uint256"}
  ],"name":"Burn","type":"event"}
]`

const pancakePoolABIJSON = `[
  {"inputs":[],"name":"slot0","outputs":[
    {"internalType":"uint160","name":"sqrtPriceX96","type":"uint160"},
    {"internalType":"int24","name":"tick","type":"int24"},
    {"internalType":"uint16","name":"observationIndex","type":"uint16"},
    {"internalType":"uint16","name":"observationCardinality","type":"uint16"},
    {"internalType":"uint16","name":"observationCardinalityNext","type":"uint16"},
    {"internalType":"uint32","name":"feeProtocol","type":"uint32"},
    {"internalType":"bool","name":"unlocked","type":"bool"}
  ],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"liquidity","outputs":[{"internalType":"uint128","name":"","type":"uint128"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"token0","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"token1","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"fee","outputs":[{"internalType":"uint24","name":"","type":"uint24"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"tickSpacing","outputs":[{"internalType":"int24","name":"","type":"int24"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"int24","name":"","type":"int24"}],"name":"ticks","outputs":[
    {"internalType":"uint128","name":"liquidityGross","type":"uint128"},
    {"internalType":"int128","name":"liquidityNet","type":"int128"},
    {"internalType":"uint256","name":"feeGrowthOutside0X128","type":"uint256"},
    {"internalType":"uint256","name":"feeGrowthOutside1X128","type":"uint256"},
    {"internalType":"int56","name":"tickCumulativeOutside","type":"int56"},
    {"internalType":"uint160","name":"secondsPerLiquidityOutsideX128","type":"uint160"},
    {"internalType":"uint32","name":"secondsOutside","type":"uint32"},
    {"internalType":"bool","name":"initialized","type":"bool"}
  ],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"int16","name":"","type":"int16"}],"name":"tickBitmap","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"anonymous":false,"inputs":[
    {"indexed":false,"internalType":"uint160","name":"sqrtPriceX96","type":"uint160"},
    {"indexed":false,"internalType":"int24","name":"tick","type":"int24"}
  ],"name":"Initialize","type":"event"},
  {"anonymous":false,"inputs":[
    {"indexed":true,"internalType":"address","name":"sender","type":"address"},
    {"indexed":true,"internalType":"address","name":"recipient","type":"address"},
    {"indexed":false,"internalType":"int256","name":"amount0","type":"int256"},
    {"indexed":false,"internalType":"int256","name":"amount1","type":"int256"},
    {"indexed":false,"internalType":"uint160","name":"sqrtPriceX96","type":"uint160"},
    {"indexed":false,"internalType":"uint128","name":"liquidity","type":"uint128"},
    {"indexed":false,"internalType":"int24","name":"tick","type":"int24"},
    {"indexed":false,"internalType":"uint128","name":"protocolFeesToken0","type":"uint128"},
    {"indexed":false,"internalType":"uint128","name":"protocolFeesToken1","type":"uint128"}
  ],"name":"Swap","type":"event"},
  {"anonymous":false,"inputs":[
    {"indexed":false,"internalType":"address","name":"sender","type":"address"},
    {"indexed":true,"internalType":"address","name":"owner","type":"address"},
    {"indexed":true,"internalType":"int24","name":"tickLower","type":"int24"},
    {"indexed":true,"internalType":"int24","name":"tickUpper","type":"int24"},
    {"indexed":false,"internalType":"uint128","name":"amount","type":"uint128"},
    {"indexed":false,"internalType":"uint256","name":"amount0","type":"uint256"},
    {"indexed":false,"internalType":"uint256","name":"amount1","type":"uint256"}
  ],"name":"Mint","type":"event"},
  {"anonymous":false,"inputs":[
    {"indexed":true,"internalType":"address","name":"owner","type":"address"},
    {"indexed":true,"internalType":"int24","name":"tickLower","type":"int24"},
    {"indexed":true,"internalType":"int24","name":"tickUpper","type":"int24"},
    {"indexed":false,"internalType":"uint128","name":"amount","type":"uint128"},
    {"indexed":false,"internalType":"uint256","name":"amount0","type":"uint256"},
    {"indexed":false,"internalType":"uint256","name":"amount1","type":"uint256"}
  ],"name":"Burn","type":"event"}
]`

const factoryABIJSON = `[
  {"inputs":[
    {"internalType":"address","name":"tokenA","type":"address"},
    {"internalType":"address","name":"tokenB","type":"address"},
    {"internalType":"uint24","name":"fee","type":"uint24"}
  ],"name":"getPool","outputs":[{"internalType":"address","name":"pool","type":"address"}],"stateMutability":"view","type":"function"}
]`

const erc20ABIJSON = `[
  {"inputs":[],"name":"symbol","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"decimals","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"}
]`

const multicallABIJSON = `[
  {"inputs":[{"components":[
    {"internalType":"address","name":"target","type":"address"},
    {"internalType":"bool","name":"allowFailure","type":"bool"},
    {"internalType":"bytes","name":"callData","type":"bytes"}
  ],"internalType":"struct Multicall3.Call3[]","name":"calls","type":"tuple[]"}],
  "name":"aggregate3","outputs":[{"components":[
    {"internalType":"bool","name":"success","type":"bool"},
    {"internalType":"bytes","name":"returnData","type":"bytes"}
  ],"internalType":"struct Multicall3.Result[]","name":"returnData","type":"tuple[]"}],
  "stateMutability":"payable","type":"function"}
]`
